// Builds src/shared/sun/timezones.gen.ts from the IANA tz database. Run: `node scripts/build-timezones.ts`.
import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const BASE_URL = "https://raw.githubusercontent.com/eggert/tz/main/";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src/shared/sun/timezones.gen.ts");

const fetchText = async (name: string) => {
  const response = await fetch(BASE_URL + name);
  if (!response.ok) throw new Error(`${name}: ${response.status}`);
  return response.text();
};

const dataLines = (text: string) =>
  text.split("\n").filter((line) => line && !line.startsWith("#"));

const toDegrees = ({
  digits,
  degreeDigits,
  sign,
}: {
  digits: string;
  degreeDigits: number;
  sign: string;
}) => {
  const degrees = Number(digits.slice(0, degreeDigits));
  const minutes = Number(digits.slice(degreeDigits, degreeDigits + 2));
  const seconds = Number(digits.slice(degreeDigits + 2) || 0);
  const value = degrees + minutes / 60 + seconds / 3600;
  return Math.round((sign === "-" ? -value : value) * 100) / 100;
};

const parseCoordinates = (iso: string) => {
  const match = /^([+-])(\d{4}(?:\d{2})?)([+-])(\d{5}(?:\d{2})?)$/.exec(iso);
  if (!match) throw new Error(`bad coordinates: ${iso}`);
  const [, latSign, latDigits, lonSign, lonDigits] = match;
  return {
    lat: toDegrees({ digits: latDigits, degreeDigits: 2, sign: latSign }),
    lon: toDegrees({ digits: lonDigits, degreeDigits: 3, sign: lonSign }),
  };
};

const [zoneText, backwardText] = await Promise.all([
  fetchText("zone1970.tab"),
  fetchText("backward"),
]);

const table: Record<string, { lat: number; lon: number }> = {};
for (const line of dataLines(zoneText)) {
  const [, coordinates, name] = line.split("\t");
  table[name] = parseCoordinates(coordinates);
}
for (const line of dataLines(backwardText)) {
  const [, target, alias] = line.split(/\s+/);
  if (table[target] && !table[alias]) table[alias] = table[target];
}

const entries = Object.keys(table)
  .sort()
  .map(
    (name) => `  ${JSON.stringify(name)}: { lat: ${table[name].lat}, lon: ${table[name].lon} },`,
  );

writeFileSync(
  out,
  `// Generated by scripts/build-timezones.ts, do not edit.\nexport const TIMEZONE_COORDINATES: Record<string, { lat: number; lon: number }> = {\n${entries.join("\n")}\n}\n`,
);
execFileSync("yarn", ["oxfmt", out], { stdio: "inherit", cwd: root });
console.log(`${entries.length} time zones written`);
