/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StreamStreamKeyRouteImport } from './routes/stream.$streamKey'
import { Route as StreamStreamKeyEntryEntryIdRouteImport } from './routes/stream.$streamKey.entry.$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamStreamKeyRoute = StreamStreamKeyRouteImport.update({
  id: '/stream/$streamKey',
  path: '/stream/$streamKey',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamStreamKeyEntryEntryIdRoute =
  StreamStreamKeyEntryEntryIdRouteImport.update({
    id: '/entry/$entryId',
    path: '/entry/$entryId',
    getParentRoute: () => StreamStreamKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/stream/$streamKey': typeof StreamStreamKeyRouteWithChildren
  '/stream/$streamKey/entry/$entryId': typeof StreamStreamKeyEntryEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/stream/$streamKey': typeof StreamStreamKeyRouteWithChildren
  '/stream/$streamKey/entry/$entryId': typeof StreamStreamKeyEntryEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/stream/$streamKey': typeof StreamStreamKeyRouteWithChildren
  '/stream/$streamKey/entry/$entryId': typeof StreamStreamKeyEntryEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscriptions'
    | '/stream/$streamKey'
    | '/stream/$streamKey/entry/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscriptions'
    | '/stream/$streamKey'
    | '/stream/$streamKey/entry/$entryId'
  id:
    | '__root__'
    | '/'
    | '/subscriptions'
    | '/stream/$streamKey'
    | '/stream/$streamKey/entry/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  StreamStreamKeyRoute: typeof StreamStreamKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$streamKey': {
      id: '/stream/$streamKey'
      path: '/stream/$streamKey'
      fullPath: '/stream/$streamKey'
      preLoaderRoute: typeof StreamStreamKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$streamKey/entry/$entryId': {
      id: '/stream/$streamKey/entry/$entryId'
      path: '/entry/$entryId'
      fullPath: '/stream/$streamKey/entry/$entryId'
      preLoaderRoute: typeof StreamStreamKeyEntryEntryIdRouteImport
      parentRoute: typeof StreamStreamKeyRoute
    }
  }
}

interface StreamStreamKeyRouteChildren {
  StreamStreamKeyEntryEntryIdRoute: typeof StreamStreamKeyEntryEntryIdRoute
}

const StreamStreamKeyRouteChildren: StreamStreamKeyRouteChildren = {
  StreamStreamKeyEntryEntryIdRoute: StreamStreamKeyEntryEntryIdRoute,
}

const StreamStreamKeyRouteWithChildren = StreamStreamKeyRoute._addFileChildren(
  StreamStreamKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  StreamStreamKeyRoute: StreamStreamKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
