export const EMPTY_SCENES = [
  "hammock",
  "bath",
  "spring",
  "autumn",
  "winter",
  "fishing",
  "cat",
  "rooftop",
  "boat",
  "beach",
  "alpine-lake",
  "bivouac",
  "hut-terrace",
  "coastal-bench",
  "lighthouse-jetty",
  "granite-cottage",
  "bike-cafe",
  "bike-canal",
  "poolside",
  "fireside",
  "paris-cafe",
  "lake-peacock",
] as const;

export type EmptyScene = (typeof EMPTY_SCENES)[number];
